# Generated by Django 5.1.1 on 2024-09-13 12:34

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='options',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
